# Generated by Django 5.0.2 on 2024-02-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
