# Generated by Django 5.0.2 on 2024-02-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_expense_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_bought',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
