# Generated by Django 5.0.2 on 2024-02-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_product_price_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
