# Generated by Django 5.0.2 on 2024-02-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_reservationpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationpayment',
            name='reservation',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='ReservationPayment',
        ),
    ]
